//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeMgEntities : DbContext
    {
        public EmployeeMgEntities()
            : base("name=EmployeeMgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
    
        public virtual ObjectResult<EmployeeList_Result> EmployeeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeList_Result>("EmployeeList");
        }
    
        public virtual ObjectResult<EmployeeLists_Result> EmployeeLists()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeLists_Result>("EmployeeLists");
        }
    }
}
